/**
 * 
 */
package it.unical.logic_santos.editor.gui.components;

/**
 * @author Agostino
 *
 */
public enum EditorStatus {
	
	ADD_OBJECT, DELETE_OBJECT, MODIFY_OBJECT, 
	ADD_ROADS_NETWORK_NODE, REMOVE_ROADS_NETWORK_NODE, MODIFY_ROADS_NETWORK_NODE,
	ADD_ROADS_NETWORK_ARC, REMOVE_ROADS_NETWORK_ARC,
	ADD_PATHS_NETWORK_NODE, REMOVE_PATHS_NETWORK_NODE, MODIFY_PATHS_NETWORK_NODE,
	ADD_PATHS_NETWORK_ARC, REMOVE_PATHS_NETWORK_ARC,
	
	UNLOAD, NDEF
}
